// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv @types/node
import "dotenv/config";
import { defineConfig } from "prisma/config";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --env-file=.env prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string | undefined,
  },
});
